[package]
name = "image-effects"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.21.2"
image = "0.23.14"
wasm-bindgen = "0.2.76"
web-sys = { version = "0.3.4", features = ["console"] }
